### ISSUE TITLE
ValueError: DataFrame constructor not properly called!

### ISSUE THREAD

**Issue by davros123** [darwinex/DarwinexLabs#19]
The python runs (sort of) but I get this error :
ValueError: DataFrame constructor not properly called!

`Exception in thread AUDNZD_Trader:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "Z:/Forex/testpath/coinflip.py", line 185, in _trader_
    10)
  File "Z:\Forex\testpath\lib\DWX_ZMQ_Reporting.py", line 55, in _get_open_trades_
    index=_response['_trades'].keys())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 422, in __init__
    raise ValueError('DataFrame constructor not properly called!')
ValueError: DataFrame constructor not properly called!`

Full pastebin here https://pastebin.com/5504A05f 

This is an example of the response data (using print statements:

```
_response= {'_action': 'OPEN_TRADES', '_trades': {96569338: {'_magic': 123456, '_symbol': 'GBPJPY', '_lots': 0.01, '_type': 1, '_open_price': 145.388, '_open_time': '2019.04.08 15:02:18', '_SL': 145.488, '_TP': 145.288, '_pnl': -0.46, '_comment': 'GBPJPY_Trader'}, 96569143: {'_magic': 123456, '_symbol': 'AUDNZD', '_lots': 0.01, '_type': 1, '_open_price': 1.05499, '_open_time': '2019.04.08 14:57:36', '_SL': 1.05599, '_TP': 1.05399, '_pnl': -0.14, '_comment': 'AUDNZD_Trader'}, 96569141: {'_magic': 123456, '_symbol': 'AUDUSD', '_lots': 0.01, '_type': 0, '_open_price': 0.71066, '_open_time': '2019.04.08 14:57:34', '_SL': 0.70966, '_TP': 0.71166, '_pnl': -0.03, '_comment': 'AUDUSD_Trader'}, 96569140: {'_magic': 123456, '_symbol': 'USDJPY', '_lots': 0.01, '_type': 1, '_open_price': 111.437, '_open_time': '2019.04.08 14:57:33', '_SL': 111.537, '_TP': 111.337, '_pnl': -0.26, '_comment': 'USDJPY_Trader'}, 96569139: {'_magic': 123456, '_symbol': 'GBPUSD', '_lots': 0.01, '_type': 1, '_open_price': 1.30538, '_open_time': '2019.04.08 14:57:32', '_SL': 1.30638, '_TP': 1.30438, '_pnl': 0.58, '_comment': 'GBPUSD_Trader'}, 96569130: {'_magic': 123456, '_symbol': 'EURUSD', '_lots': 0.01, '_type': 0, '_open_price': 1.12479, '_open_time': '2019.04.08 14:57:17', '_SL': 1.12379, '_TP': 1.12579, '_pnl': -0.28, '_comment': 'EURUSD_Trader'}, 96569107: {'_magic': 123456, '_symbol': 'EURCAD', '_lots': 0.01, '_type': 0, '_open_price': 1.50396, '_open_time': '2019.04.08 14:56:18', '_SL': 1.50296, '_TP': 1.50496, '_pnl': 0.1, '_comment': 'EURCAD_Trader'}, 96569106: {'_magic': 123456, '_symbol': 'NZDCHF', '_lots': 0.01, '_type': 0, '_open_price': 0.67343, '_open_time': '2019.04.08 14:56:17', '_SL': 0.67243, '_TP': 0.67443, '_pnl': 0.02, '_comment': 'NZDCHF_Trader'}}}

_response['_trades'].values()= dict_values([{'_magic': 123456, '_symbol': 'GBPJPY', '_lots': 0.01, '_type': 1, '_open_price': 145.388, '_open_time': '2019.04.08 15:02:18', '_SL': 145.488, '_TP': 145.288, '_pnl': -0.46, '_comment': 'GBPJPY_Trader'}, {'_magic': 123456, '_symbol': 'AUDNZD', '_lots': 0.01, '_type': 1, '_open_price': 1.05499, '_open_time': '2019.04.08 14:57:36', '_SL': 1.05599, '_TP': 1.05399, '_pnl': -0.14, '_comment': 'AUDNZD_Trader'}, {'_magic': 123456, '_symbol': 'AUDUSD', '_lots': 0.01, '_type': 0, '_open_price': 0.71066, '_open_time': '2019.04.08 14:57:34', '_SL': 0.70966, '_TP': 0.71166, '_pnl': -0.03, '_comment': 'AUDUSD_Trader'}, {'_magic': 123456, '_symbol': 'USDJPY', '_lots': 0.01, '_type': 1, '_open_price': 111.437, '_open_time': '2019.04.08 14:57:33', '_SL': 111.537, '_TP': 111.337, '_pnl': -0.26, '_comment': 'USDJPY_Trader'}, {'_magic': 123456, '_symbol': 'GBPUSD', '_lots': 0.01, '_type': 1, '_open_price': 1.30538, '_open_time': '2019.04.08 14:57:32', '_SL': 1.30638, '_TP': 1.30438, '_pnl': 0.58, '_comment': 'GBPUSD_Trader'}, {'_magic': 123456, '_symbol': 'EURUSD', '_lots': 0.01, '_type': 0, '_open_price': 1.12479, '_open_time': '2019.04.08 14:57:17', '_SL': 1.12379, '_TP': 1.12579, '_pnl': -0.28, '_comment': 'EURUSD_Trader'}, {'_magic': 123456, '_symbol': 'EURCAD', '_lots': 0.01, '_type': 0, '_open_price': 1.50396, '_open_time': '2019.04.08 14:56:18', '_SL': 1.50296, '_TP': 1.50496, '_pnl': 0.1, '_comment': 'EURCAD_Trader'}, {'_magic': 123456, '_symbol': 'NZDCHF', '_lots': 0.01, '_type': 0, '_open_price': 0.67343, '_open_time': '2019.04.08 14:56:17', '_SL': 0.67243, '_TP': 0.67443, '_pnl': 0.02, '_comment': 'NZDCHF_Trader'}])

_response['_trades'].keys()= dict_keys([96569338, 96569143, 96569141, 96569140, 96569139, 96569130, 96569107, 96569106])

```
```

DWX_ZMQ_Reporting():
`# -*- coding: utf-8 -*-
"""
    DWX_ZMQ_Reporting.py
    --
    @author: Darwinex Labs (www.darwinex.com)
    
    Copyright (c) 2019 onwards, Darwinex. All rights reserved.
    
    Licensed under the BSD 3-Clause License, you may not use this file except 
    in compliance with the License. 
    
    You may obtain a copy of the License at:    
    https://opensource.org/licenses/BSD-3-Clause
"""

from pandas import DataFrame, to_datetime
from time import sleep

class DWX_ZMQ_Reporting():
    
    def __init__(self, _zmq):
        self._zmq = _zmq
        
    ##########################################################################
    
    def _get_open_trades_(self, _trader='Trader_SYMBOL', 
                          _delay=0.1, _wbreak=10):
        
        # Reset data output
        self._zmq._set_response_(None)
        
        # Get open trades from MetaTrader
        self._zmq._DWX_MTX_GET_ALL_OPEN_TRADES_()

        # While loop start time reference            
        _ws = to_datetime('now')
        
        # While data not received, sleep until timeout
        while self._zmq._valid_response_('zmq') == False:
            
            sleep(_delay)
            
            if (to_datetime('now') - _ws).total_seconds() > (_delay * _wbreak):
                break
        
        # If data received, return DataFrame
        if self._zmq._valid_response_('zmq'):
            
            _response = self._zmq._get_response_()
            
            if ('_trades' in _response.keys()
                and len(_response['_trades']) > 0):
                
                _df = DataFrame(data=_response['_trades'].values(),
                                index=_response['_trades'].keys())
                return _df[_df['_comment'] == _trader]
            
        # Default
        return DataFrame()
    
    ##########################################################################
    

````

**Comment by davros123** [comment]
Solution as per here ... [https://markhneedham.com/blog/2017/03/19/python-3-typeerror-object-type-dict_values-not-json-serializable/]

using list works...
```
                _df = DataFrame(list(_response['_trades'].values()),
                                list(_response['_trades'].keys()))
```
